### ISSUE TITLE
v0.0.4 breaks

### ISSUE THREAD

**Issue by edxeth** [franlol/opencode-md-table-formatter#10]
`@franlol/opencode-md-table-formatter@0.0.4` throws the following error on startup using OpenCode v1.2.10:

```json
{
  "name": "UnknownError",
  "data": {
    "message": "TypeError: text.split is not a function. (In 'text.split(`\n`)', 'text.split' is undefined)\n
 at formatMarkdownTables (/home/devkit/.cache/opencode/node_modules/@franlol/opencode-md-table-formatter/index.ts:26:22)\n    at <anonymous> (src/plugin/index.ts:90:28)\n    at processTicksAndRejections (native:7:39)"
  }
}
```

The older releases seem to be working just fine. The regression seem to be in https://github.com/franlol/opencode-md-table-formatter/commit/1ff1c1eaf859bf2277b4958660268a6ddb15c68c.

**Comment by infernalsirius** [comment]
same here.

**Comment by harrison-pan** [comment]
same here

{
  "name": "UnknownError",
  "data": {
    "message": "TypeError: text.split is not a function. (In 'text.split(`\n`)', 'text.split' is undefined)\n    at formatMarkdownTables (/Users/harrisonpan/.cache/opencode/node_modules/@franlol/opencode-md-table-formatter/index.ts:26:22)\n    at <anonymous> (src/plugin/index.ts:90:28)\n    at processTicksAndRejections (native:7:39)"
  }
}

**Comment by franlol** [comment]
Already checking

**Comment by potb** [comment]
0.0.6 fixed it for me, thanks for the reactivity

**Comment by harrison-pan** [comment]
0.0.6 works. Thanks
